packages:
  - "apps/admin"
  - "apps/backend"
  - "apps/frontend"
  - "apps/letstry-mobile"
  - "apps/ota-sdui-server"
  - "apps/proof_app/PackVerifyApp"
  - "packages/*"

onlyBuiltDependencies:
  - "@react-native-clipboard/clipboard"
